### ISSUE TITLE
[Suggestion] Remove only vanilla flowers

### ISSUE THREAD

**Issue by Skillotic0703** [superfluke/goodbyegrass#1]
Your mod currently removes all flowers. I was intending to use it to disable vanilla flower generation and replace it with botania flowers but that's not possible because it also removes botania flowers.

**Comment by superfluke** [comment]
Took a look into this and I don't think it's possible with this mod. This is because I'm not actually disabling the botania flowers, rather the botania flowers wait until it sees vanilla flowers generating then adds its own flowers to the same chunk. So when no vanilla flowers generate, no botania flowers generate. 
You could use something like COFH world to add botania flowers.
